name: xlfz
description: "一个心理相关的软件"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  intl: ^0.18.0
  provider: ^6.1.2
  shrine_images: ^2.0.2
  percent_indicator: ^4.2.3
  fl_chart: ^0.62.0
  flutter_launcher_icons: ^0.12.0
  http: ^0.13.6
  shared_preferences: ^2.2.2
  fluttertoast: ^7.1.0
  connectivity_plus: ^5.0.2
  image_picker: ^1.0.2
  speech_to_text: ^5.5.0
  flutter_tts: ^4.0.2
  permission_handler: ^8.0.0
  table_calendar: ^3.0.2
  path: ^1.8.2
  drift: ^2.0.0
  path_provider: ^2.0.0



dev_dependencies:
  pedantic: ^1.11.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  drift_dev: ^2.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: false
  ios: true
  image_path: "lib/assets/icon/app_icon.jpg"  # 这里设置图标的路径