name: xlfz
description: "一个心理相关的软件"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  provider: ^6.1.2
  shrine_images: ^2.0.2
  percent_indicator: ^4.2.3
  fl_chart: ^0.69.0
  flutter_launcher_icons: ^0.14.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  fluttertoast: ^8.2.8
  connectivity_plus: ^6.1.0
  emoji_picker_flutter: ^3.1.0
  image_picker: ^1.1.2
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2
  permission_handler: ^11.1.0+2
  table_calendar: ^3.0.0


dev_dependencies:
  pedantic: ^1.11.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: false
  ios: true
  image_path: "lib/assets/icon/app_icon.jpg"  # 这里设置图标的路径