name: Build Flutter App

on:
  push:
    branches:
      - master  # 当推送到 master 分支时触发构建

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      - name: Clean Flutter Project
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Verify Info.plist Content
        run: cat ios/Runner/Info.plist

      - name: Build iOS IPA (Unsigned)
        run: flutter build ipa --release --no-codesign

      - name: List build directory
        run: ls -R build/ios

      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: Runner.ipa
          path: build/ios/ipa/*.ipa
